import os
import glob
import re
from PIL import Image, ImageFont, ImageDraw

# Configuration
FONT_PATH = "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc"
# Fallback to Medium if Regular doesn't exist, or just auto-detect
if not os.path.exists(FONT_PATH):
    FONT_PATH = "/usr/share/fonts/noto-cjk/NotoSansCJK-Medium.ttc"

OUTPUT_FILE = "font_zh.py"
FONT_SIZE = 16  # 16x16 pixels

def get_chinese_chars(directory="."):
    """Scans all .py files for Chinese characters."""
    chinese_chars = set()
    # Range for common CJK Unified Ideographs
    pattern = re.compile(r'[\u4e00-\u9fff]')
    
    files = glob.glob(os.path.join(directory, "*.py"))
    for fpath in files:
        if fpath.endswith(OUTPUT_FILE) or fpath.endswith("compile_font.py"):
            continue
            
        with open(fpath, 'r', encoding='utf-8') as f:
            content = f.read()
            found = pattern.findall(content)
            chinese_chars.update(found)
            
    return sorted(list(chinese_chars))

def render_char_bitmap(font, char):
    """Renders a character to a bit bytearray (0=Black/Text, 1=White/Background)."""
    # Create a blank image (White background = 1)
    image = Image.new("1", (FONT_SIZE, FONT_SIZE), 1)
    draw = ImageDraw.Draw(image)
    
    # Calculate centering
    try:
        # getbbox returns (left, top, right, bottom)
        bbox = font.getbbox(char)
        if bbox:
            box_h = bbox[3] - bbox[1]
            # Center vertically: (16 - height) // 2
            # We also subtract bbox[1] (top) to shift the glyph up/down correctly
            y_offset = ((FONT_SIZE - box_h) // 2) - bbox[1]
        else:
            y_offset = -1 # Fallback
    except Exception:
        y_offset = -1

    # Draw text (Black = 0)
    draw.text((0, y_offset), char, font=font, fill=0)
    
    # Extract bytes for MONO_HLSB
    pixels = image.load()
    buffer = bytearray()
    
    for y in range(FONT_SIZE):
        byte_val = 0
        for x in range(0, 8):
            if pixels[x, y]: # If pixel is 1 (White)
                byte_val |= (1 << (7 - x))
        buffer.append(byte_val)
        
        byte_val = 0
        for x in range(8, 16):
            if pixels[x, y]:
                byte_val |= (1 << (15 - x))
        buffer.append(byte_val)
        
    return buffer
def generate_font_file(chars):
    print(f"Generating font_zh.py and font_data.bin with {len(chars)} characters")
    
    try:
        font = ImageFont.truetype(FONT_PATH, FONT_SIZE)
    except IOError:
        print(f"Error: Could not load font at {FONT_PATH}")
        return

    # 1. Generate Binary Data and Index
    index = {}
    with open("font_data.bin", "wb") as bin_file:
        offset = 0
        for char in chars:
            bitmap = render_char_bitmap(font, char)
            bin_file.write(bitmap)
            index[char] = offset
            offset += 32 # 16x16 = 256 bits = 32 bytes

    # 2. Generate Python Driver
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("# Auto-generated by compile_font.py (File-Backed)\n")
        f.write("import framebuf\n\n")
        
        # Write the Index
        f.write("INDEX = {\n")
        for char, off in index.items():
            f.write(f'    "{char}": {off},\n')
        f.write("}\n\n")
        
        # Add the draw functions
        f.write("""def draw_char(fb, char, x, y):
    if char not in INDEX: return
    offset = INDEX[char]
    
    # Read from file (Lazy Load)
    try:
        with open('font_data.bin', 'rb') as f:
            f.seek(offset)
            data = f.read(32)
    except OSError:
        return

    char_fb = framebuf.FrameBuffer(bytearray(data), 16, 16, framebuf.MONO_HLSB)
    fb.blit(char_fb, x, y)

def draw_text(fb, text, x, y):
    cursor = x
    for char in text:
        if char in INDEX:
            draw_char(fb, char, cursor, y)
            cursor += 16
        elif 32 <= ord(char) <= 126:
            fb.text(char, cursor, y + 4, 0)
            cursor += 8
        else:
            fb.text("?", cursor, y + 4, 0)
            cursor += 8
""")

if __name__ == "__main__":
    chars = get_chinese_chars()
    if chars:
        generate_font_file(chars)
    else:
        print("No Chinese characters found in .py files.")
